version: '2.1'

services:
  janusgraph:
    image: chrislbs/janusgraph:latest
    container_name: janusgraph-cassandra-es
    environment:
      JANUS_STORAGE_BACKEND: astyanax
      JANUS_STORAGE_HOSTNAME: cassandra-host
      JANUS_INDEX_DEFINED_NAME: search
      JANUS_INDEX_HOSTNAME: elasticsearch
    ports:
      - "8182:8182"
    links:
      - cassandra:cassandra-host
      - elastic-search:elasticsearch
    depends_on:
      cassandra:
        condition: service_healthy
      elastic-search:
        condition: service_healthy
    healthcheck:
        test: [ "CMD-SHELL", "timeout -t 2 bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/8182'" ]
        interval: 10s
        timeout: 10s
        retries: 6

  cassandra:
    image: cassandra:2.2.9
    container_name: cassandra2
    ports:
      - "9042:9042"
      - "9160:9160"
    environment:
      CASSANDRA_START_RPC: 'true'
    healthcheck:
      test: [ "CMD-SHELL", "timeout 2 bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/9160'" ]
      interval: 10s
      timeout: 10s
      retries: 6

  elastic-search:
    image: elasticsearch:2.4.5
    container_name: elastic2
    ports:
      - "9200:9200"
    healthcheck:
        test: [ "CMD-SHELL", "timeout 2 bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/9200'" ]
        interval: 10s
        timeout: 10s
        retries: 6
